
version: "2"
services:

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022 #optional
    volumes:
      - /media/usbdisk/config/sonarr:/config
      - /media/usbdisk/tv-shows:/tv
      - /media/usbdisk/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022 #optional
    volumes:
      - /media/usbdisk/config/radarr:/config
      - /media/usbdisk/movies:/movies
      - /media/usbdisk/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=timezone
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /media/usbdisk/config/deluge:/config
      - /media/usbdisk/downloads:/downloads
    ports:
      - 8112:8112
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
    volumes:
      - /media/usbdisk/config/plex:/config
      - /media/usbdisk/tv-shows:/tv
      - /media/usbdisk/movies:/movies
      - /media/usbdisk/transcode:/transcode
    ports:
      - 32400:32400
      - 33400:33400
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022 #optional
    volumes:
      - /media/usbdisk/config/bazaar:/config
      - /media/usbdisk/movies:/movies
      - /media/usbdisk/tv-shows:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

