version: "2"
services:

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022
    volumes:
      - /media/usbdisk/config/sonarr:/config
      - /media/usbdisk/tv-shows:/tv
      - /media/usbdisk/downloads:/downloads
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022
    volumes:
      - /media/usbdisk/config/radarr:/config
      - /media/usbdisk/movies:/movies
      - /media/usbdisk/downloads:/downloads
    restart: unless-stopped

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022
      - DELUGE_LOGLEVEL=error
    volumes:
      - /media/usbdisk/config/deluge:/config
      - /media/usbdisk/downloads:/downloads
      - /media/usbdisk/blackhole:/blackhole
      - /media/usbdisk/other-downloads:/other-downloads
    ports:
      - 8112:8112
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022
    volumes:
      - /media/usbdisk/config/bazarr:/config
      - /media/usbdisk/movies:/movies
      - /media/usbdisk/tv-shows:/tv
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /media/usbdisk/config/jackett:/config
      - /media/usbdisk/blackhole:/downloads
    restart: unless-stopped

  emby:
    image: linuxserver/emby
    container_name: emby
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022
    volumes:
      - /media/usbdisk/config/emby:/config
      - /media/usbdisk/tv-shows:/tv
      - /media/usbdisk/movies:/movies
      - /media/usbdisk/other-downloads:/other-downloads
      - /media/usbdisk/transcode:/transcode
    restart: unless-stopped
